### ISSUE TITLE
camera_tf_trt.py error

### ISSUE THREAD

**Issue by WhaSukGO** [jkjung-avt/tf_trt_models#11]
Than you for the great tutorial.

I tried the code with my custom model.

I used `faster_rcnn_resnet50`
My Tensorflow version is 1.15.0.
Jetpack 4.3 / Jetson Nano

However, when I run the code, it throws an error.

```
ubuntu@ubuntu:~/project/tf_trt_models$ python3 camera_tf_trt.py --usb --model faster_rcnn_resnet50_egohands --labelmap data/label.pbtxt --num-classes 1
2020-05-21 12:25:08.193087: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-05-21 12:25:23.568053: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-05-21 12:25:23.588421: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

INFO:__main__:called with args: Namespace(conf_th=0.3, do_build=False, do_tensorboard=False, filename=None, image_height=480, image_width=640, labelmap_file='data/label.pbtxt', model='faster_rcnn_resnet50_egohands', num_classes=1, rtsp_latency=200, rtsp_uri=None, use_file=False, use_image=False, use_rtsp=False, use_usb=True, video_dev=0)
INFO:__main__:reading label map
WARNING:tensorflow:From /home/whasukgo-1/.local/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/utils/label_map_util.py:131: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

INFO:__main__:opening camera device/file
[ WARN:0] global /home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp (933) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
INFO:__main__:loading TRT graph from pb: ./data/faster_rcnn_resnet50_egohands_trt.pb
WARNING:tensorflow:From /home/whasukgo-1/project/tf_trt_models/utils/od_utils.py:71: The name tf.GraphDef is deprecated. Please use tf.compat.v1.GraphDef instead.

INFO:__main__:starting up TensorFlow session
WARNING:tensorflow:From camera_tf_trt.py:170: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From camera_tf_trt.py:172: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2020-05-21 12:25:33.667944: W tensorflow/core/platform/profile_utils/cpu_utils.cc:98] Failed to find bogomips in /proc/cpuinfo; cannot determine CPU frequency
2020-05-21 12:25:33.668519: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1ebb7090 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-05-21 12:25:33.668591: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-05-21 12:25:33.740586: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-05-21 12:25:33.873376: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:950] ARM64 does not support NUMA - returning NUMA node zero
2020-05-21 12:25:33.873689: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2008ed80 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-05-21 12:25:33.873774: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA Tegra X1, Compute Capability 5.3
2020-05-21 12:25:33.874331: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:950] ARM64 does not support NUMA - returning NUMA node zero
2020-05-21 12:25:33.874478: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: NVIDIA Tegra X1 major: 5 minor: 3 memoryClockRate(GHz): 0.9216
pciBusID: 0000:00:00.0
2020-05-21 12:25:33.874708: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-05-21 12:25:33.874898: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-05-21 12:25:33.979043: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-05-21 12:25:34.107917: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-05-21 12:25:34.240839: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-05-21 12:25:34.316446: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-05-21 12:25:34.316897: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-05-21 12:25:34.317290: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:950] ARM64 does not support NUMA - returning NUMA node zero
2020-05-21 12:25:34.317662: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:950] ARM64 does not support NUMA - returning NUMA node zero
2020-05-21 12:25:34.317788: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-05-21 12:25:34.317970: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-05-21 12:25:41.222625: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-05-21 12:25:41.222729: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-05-21 12:25:41.222767: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-05-21 12:25:41.223276: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:950] ARM64 does not support NUMA - returning NUMA node zero
2020-05-21 12:25:41.223731: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:950] ARM64 does not support NUMA - returning NUMA node zero
2020-05-21 12:25:41.223935: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 71 MB memory) -> physical GPU (device: 0, name: NVIDIA Tegra X1, pci bus id: 0000:00:00.0, compute capability: 5.3)
INFO:__main__:warming up the TRT graph with a dummy image
Traceback (most recent call last):
  File "/home/whasukgo-1/.local/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/whasukgo-1/.local/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1348, in _run_fn
    self._extend_graph()
  File "/home/whasukgo-1/.local/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1388, in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot colocate nodes {{colocation_node SecondStagePostprocessor/BatchMultiClassNonMaxSuppression/map/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3}} and {{colocation_node SecondStagePostprocessor/Reshape_4}}: Cannot merge devices with incompatible types: '/device:CPU:0' and '/device:GPU:0'
	 [[{{node SecondStagePostprocessor/BatchMultiClassNonMaxSuppression/map/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "camera_tf_trt.py", line 199, in <module>
    main()
  File "camera_tf_trt.py", line 181, in main
    _, _, _ = detect(dummy_img, tf_sess, conf_th=.3, od_type=od_type)
  File "/home/whasukgo-1/project/tf_trt_models/utils/od_utils.py", line 141, in detect
    feed_dict={tf_input: img[None, ...]})
  File "/home/whasukgo-1/.local/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/whasukgo-1/.local/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/whasukgo-1/.local/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/whasukgo-1/.local/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot colocate nodes node SecondStagePostprocessor/BatchMultiClassNonMaxSuppression/map/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3 (defined at /home/whasukgo-1/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) placed on device No device assignments were active during op 'SecondStagePostprocessor/BatchMultiClassNonMaxSuppression/map/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3' creation.  and node SecondStagePostprocessor/Reshape_4 (defined at /home/whasukgo-1/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) placed on device Device assignments active during op 'SecondStagePostprocessor/Reshape_4' creation:
  with tf.device(/device:GPU:0): </home/whasukgo-1/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/importer.py:80> : Cannot merge devices with incompatible types: '/device:CPU:0' and '/device:GPU:0'
	 [[node SecondStagePostprocessor/BatchMultiClassNonMaxSuppression/map/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3 (defined at /home/whasukgo-1/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]Additional information about colocations:No node-device colocations were active during op 'SecondStagePostprocessor/BatchMultiClassNonMaxSuppression/map/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3' creation.
No device assignments were active during op 'SecondStagePostprocessor/BatchMultiClassNonMaxSuppression/map/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3' creation.
No node-device colocations were active during op 'SecondStagePostprocessor/Reshape_4' creation.
Device assignments active during op 'SecondStagePostprocessor/Reshape_4' creation:
  with tf.device(/device:GPU:0): </home/whasukgo-1/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/importer.py:80>

Original stack trace for 'SecondStagePostprocessor/BatchMultiClassNonMaxSuppression/map/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3':
  File "camera_tf_trt.py", line 199, in <module>
    main()
  File "camera_tf_trt.py", line 167, in main
    trt_graph = load_trt_pb(pb_path)
  File "/home/whasukgo-1/project/tf_trt_models/utils/od_utils.py", line 83, in load_trt_pb
    tf.import_graph_def(trt_graph_def, name='')
  File "/home/whasukgo-1/.local/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/whasukgo-1/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/home/whasukgo-1/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/importer.py", line 517, in _import_graph_def_internal
    _ProcessNewOps(graph)
  File "/home/whasukgo-1/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/importer.py", line 243, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "/home/whasukgo-1/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3561, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "/home/whasukgo-1/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3561, in <listcomp>
    for c_op in c_api_util.new_tf_operations(self)
  File "/home/whasukgo-1/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3451, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "/home/whasukgo-1/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

```

**Comment by jkjung-avt** [comment]
Refer to my [JetPack-4.3 for Jetson Nano](https://jkjung-avt.github.io/jetpack-4.3/) blog post.  This is how I modified the code to make the ssd models run on JetPack-4.3 and tensorflow-1.15.0.  You probably need to do similar modifications for faster_rcnn.

```
diff --git a/utils/od_utils.py b/utils/od_utils.py
index 2755bb5..b8ebe1b 100644
--- a/utils/od_utils.py
+++ b/utils/od_utils.py
@@ -52,7 +52,9 @@ def build_trt_pb(model_name, pb_path, download_dir='data'):
             get_egohands_model(model_name)
     frozen_graph_def, input_names, output_names = build_detection_graph(
         config=config_path,
-        checkpoint=checkpoint_path
+        checkpoint=checkpoint_path,
+        force_nms_cpu=False,
+        force_frcn2_cpu=False,
     )
     trt_graph_def = trt.create_inference_graph(
         input_graph_def=frozen_graph_def,
@@ -77,8 +79,8 @@ def load_trt_pb(pb_path):
             node.device = '/device:GPU:0'
         if 'faster_rcnn_' in pb_path and 'SecondStage' in node.name:
             node.device = '/device:GPU:0'
-        if 'NonMaxSuppression' in node.name:
-            node.device = '/device:CPU:0'
+        #if 'NonMaxSuppression' in node.name:
+        #    node.device = '/device:CPU:0'
     with tf.Graph().as_default() as trt_graph:
         tf.import_graph_def(trt_graph_def, name='')
     return trt_graph
```

**Comment by gpqls** [comment]
I'm using Jetpack 4.2.1, and the tensorflow version is 1.14.0. The same error was corrected in this version. Thanks!!!!

**Comment by jkjung-avt** [comment]
That's great.  Thanks for the update.
